### ISSUE TITLE
Transcoders does not appear to be installed.

### ISSUE THREAD

**Issue by sedlund** [ulikoenig/subsonic-patched#1]
line 39/40 of Dockerfile should reference /var/subsonic/transcode not /var/lib/subsonic/transcode.

Currently subsonic will not find the transcode binaries and complain in Settings -> Players

"Notice: Transcoders does not appear to be installed.
Click Help button for more information."

**Comment by ulikoenig** [comment]
Thanks for the Bugreport. I fixed it. Error message is gone in my installation.

Please check if it worked for you, too.

**Comment by sedlund** [comment]
thanks this can be closed
